apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw06-app
  labels:
    app: hw06-app
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw06-app
  template:
    metadata:
      labels:
        app: hw06-app
        version: "1.0"
    spec:
      containers:
        - name: hw06-app
          image: hw06-cr-demo.cr.yandex/hw06-app:1.0
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"

          # Проверки здоровья
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          # Ресурсы
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"

          # Безопасность
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: hw06-app-service
  labels:
    app: hw06-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: hw06-app
